model: fff.ManifoldFreeFormFlow

data_set:
  name: hyperbolic_toy
  subtype: checkerboard

noise: 0.0

latent_distribution:
  name: manifold-wrapped-standard-normal
  tangent_scale: 0.5

loss_weights:
  nll: 1
  noisy_reconstruction: 100
  z_reconstruction: 100
  x_sample_reconstruction: 100
  x1_projection: 100
  z_projection: 100
manifold_distance: False

models:
  - name: fff.model.ResNet
    latent_dim: data
    layers_spec:
      [
        [256, 256, 256],
        [256, 256, 256],
        [256, 256, 256],
        [256, 256, 256],
        [256, 256, 256],
        [256, 256, 256],
      ]
    activation: "silu"

optimizer:
  name: adam
  lr: 0.001
  weight_decay: 0.001

lr_scheduler:
  name: ExponentialLR
  kwargs:
    gamma: 0.9981
  interval: epoch
max_epochs: 3600
batch_size: 4096

accelerator: "gpu"
num_workers: 0

model_checkpoint:
  monitor: "auto"
  save_last: True
  every_n_epochs: 5
  save_top_k: 5
